### ISSUE TITLE
Better handling of long code in Python Book

### ISSUE THREAD

**Issue by admiyo** [r1chardj0n3s/pycode-minecraft#2]
If  the python code gets too long, you cannot scroll to all of it.  I compared the python book to the regular book, and the "next" button made a huge difference.  For something non trivial, I'd end up with one function per page, I think.  Is the python book based on the regular book?  Is something hiding the page buttons?

**Comment by r1chardj0n3s** [comment]
I need to come up with a better handling of long code - the book already has pages with next/previous buttons like the standard writeable book, but the problem is that if you have a code block that goes over a page break it's kinda unreadable. You can do it right now, though, since the pages are just concatenated before compilation.

Please double-check you're not seeing the next button - if you're not then something bad is happening. The next page button is in the top right - I just realised it's not got great visibility.

Unfortunately I can't get scroll-wheel events in the GUI (AFAICT). I'll probably remove the multi-page handling and replace it with a single page, scrollbar and arrow key scrolling. It's a bunch of work though which I need to find the enthusiasm for ;-)

**Comment by admiyo** [comment]
Ah I see the back and forward buttons at the top of the page.  Trying to add code to the second page caused a crash.  Report below.

Please leave the buttons.  I think one function per page will work well...I'd almost like the first or last page to be a hyperlinked index  based on the first line of the page.

---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 12/14/16 9:58 PM
Description: Rendering screen

java.lang.ArrayIndexOutOfBoundsException: -19
	at net.mechanicalcat.pycode.gui.GuiPythonBook.func_73863_a(GuiPythonBook.java:300)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.mechanicalcat.pycode.gui.GuiPythonBook.func_73863_a(GuiPythonBook.java:300)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)

-- Screen render details --
Details:
	Screen name: net.mechanicalcat.pycode.gui.GuiPythonBook
	Mouse location: Scaled: (239, 54). Absolute: (958, 798)
	Screen size: Scaled: (480, 254). Absolute: (1920, 1016). Scale factor of 4

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['admiyo'/226, l='MpServer', x=-74.50, y=69.00, z=136.50]]
	Chunk stats: MultiplayerChunkCache: 550, 550
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-68,64,144), Chunk: (at 12,4,0 in -5,9; contains blocks -80,0,144 to -65,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1947 game time, 1947 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 72 total; [EntityZombie['Zombie'/129, l='MpServer', x=-62.24, y=30.00, z=82.67], EntityZombie['Zombie'/130, l='MpServer', x=-59.50, y=29.00, z=87.50], EntityZombie['Zombie'/131, l='MpServer', x=-58.50, y=29.00, z=86.50], EntityCreeper['Creeper'/132, l='MpServer', x=-52.50, y=35.00, z=120.50], EntityCreeper['Creeper'/133, l='MpServer', x=-52.50, y=35.00, z=120.50], EntitySkeleton['Skeleton'/134, l='MpServer', x=-53.50, y=35.00, z=143.50], EntityCreeper['Creeper'/135, l='MpServer', x=-50.50, y=34.00, z=153.50], EntityItem['item.tile.torch'/136, l='MpServer', x=-58.22, y=35.00, z=168.37], EntityCreeper['Creeper'/9, l='MpServer', x=-151.50, y=14.00, z=106.50], EntityMinecartChest['Minecart with Chest'/137, l='MpServer', x=-57.50, y=35.06, z=168.50], EntityZombie['Zombie'/138, l='MpServer', x=-49.50, y=35.00, z=168.50], EntityBat['Bat'/139, l='MpServer', x=-65.77, y=17.34, z=208.33], EntitySkeleton['Skeleton'/144, l='MpServer', x=-39.73, y=35.00, z=119.53], EntitySkeleton['Skeleton'/145, l='MpServer', x=-40.50, y=36.00, z=125.50], EntityCreeper['Creeper'/146, l='MpServer', x=-42.50, y=36.00, z=122.50], EntitySkeleton['Skeleton'/147, l='MpServer', x=-40.50, y=36.00, z=130.50], EntityZombie['Zombie'/148, l='MpServer', x=-42.26, y=36.00, z=132.44], EntitySkeleton['Skeleton'/149, l='MpServer', x=-39.30, y=34.00, z=152.40], EntityZombie['Zombie'/167, l='MpServer', x=-28.25, y=34.00, z=124.48], EntityZombie['Zombie'/168, l='MpServer', x=-24.75, y=34.00, z=124.61], EntitySkeleton['Skeleton'/169, l='MpServer', x=-17.50, y=15.00, z=149.50], EntityCreeper['Creeper'/170, l='MpServer', x=-26.50, y=20.00, z=151.50], EntityCreeper['Creeper'/171, l='MpServer', x=-27.50, y=20.00, z=154.50], EntityBat['Bat'/173, l='MpServer', x=-11.87, y=14.00, z=174.89], EntityZombie['Zombie'/179, l='MpServer', x=-3.50, y=12.00, z=166.50], EntityZombie['Zombie'/180, l='MpServer', x=-9.50, y=28.00, z=201.50], EntityZombie['Zombie'/181, l='MpServer', x=-6.65, y=17.00, z=206.35], EntitySpider['Spider'/57, l='MpServer', x=-139.50, y=41.00, z=72.50], EntityCreeper['Creeper'/185, l='MpServer', x=5.50, y=31.00, z=165.50], EntityBat['Bat'/58, l='MpServer', x=-136.25, y=40.82, z=73.34], EntityBat['Bat'/59, l='MpServer', x=-123.02, y=21.75, z=138.14], EntityCreeper['Creeper'/60, l='MpServer', x=-134.30, y=14.00, z=171.70], EntityZombie['Zombie'/61, l='MpServer', x=-138.19, y=14.00, z=173.48], EntityEnderman['Enderman'/62, l='MpServer', x=-130.45, y=21.00, z=160.48], EntityCreeper['Creeper'/191, l='MpServer', x=0.50, y=25.00, z=213.50], EntitySkeleton['Skeleton'/74, l='MpServer', x=-113.50, y=26.00, z=83.72], EntityZombie['Zombie'/75, l='MpServer', x=-112.82, y=27.00, z=84.90], EntityZombie['Zombie'/76, l='MpServer', x=-114.23, y=27.00, z=85.61], EntityChicken['Chicken'/77, l='MpServer', x=-114.50, y=23.00, z=133.50], EntityEnderman['Enderman'/78, l='MpServer', x=-119.50, y=16.00, z=154.50], EntitySkeleton['Skeleton'/79, l='MpServer', x=-116.50, y=23.00, z=183.50], EntityZombie['Zombie'/80, l='MpServer', x=-105.29, y=28.00, z=93.49], EntityZombie['Zombie'/81, l='MpServer', x=-109.50, y=28.00, z=89.24], EntityZombie['Zombie'/82, l='MpServer', x=-108.80, y=27.00, z=83.51], EntityBat['Bat'/83, l='MpServer', x=-108.21, y=26.00, z=88.06], EntityCreeper['Creeper'/84, l='MpServer', x=-102.50, y=18.00, z=167.50], EntityCreeper['Creeper'/85, l='MpServer', x=-104.50, y=18.00, z=167.50], EntityCreeper['Creeper'/86, l='MpServer', x=-102.19, y=15.00, z=177.50], EntitySkeleton['Skeleton'/87, l='MpServer', x=-92.65, y=23.02, z=212.20], EntityPlayerSP['admiyo'/226, l='MpServer', x=-74.50, y=69.00, z=136.50], EntitySkeleton['Skeleton'/102, l='MpServer', x=-81.52, y=24.00, z=63.21], EntityCreeper['Creeper'/103, l='MpServer', x=-85.50, y=30.00, z=96.50], EntitySkeleton['Skeleton'/104, l='MpServer', x=-92.50, y=21.00, z=201.50], EntitySkeleton['Skeleton'/105, l='MpServer', x=-88.50, y=23.00, z=206.27], EntitySkeleton['Skeleton'/106, l='MpServer', x=-83.50, y=22.00, z=196.50], EntityEnderman['Enderman'/107, l='MpServer', x=-87.50, y=22.00, z=201.50], EntityCreeper['Creeper'/108, l='MpServer', x=-82.50, y=22.00, z=202.50], EntityCreeper['Creeper'/109, l='MpServer', x=-82.50, y=22.00, z=204.50], EntityBat['Bat'/110, l='MpServer', x=-71.33, y=19.26, z=211.85], EntitySkeleton['Skeleton'/111, l='MpServer', x=-90.50, y=13.00, z=209.50], EntitySkeleton['Skeleton'/112, l='MpServer', x=-88.50, y=15.00, z=213.50], EntitySkeleton['Skeleton'/117, l='MpServer', x=-77.50, y=22.00, z=65.50], EntityBat['Bat'/118, l='MpServer', x=-81.37, y=24.72, z=59.58], EntitySpider['Spider'/119, l='MpServer', x=-76.50, y=31.00, z=93.50], EntityCreeper['Creeper'/120, l='MpServer', x=-66.50, y=29.00, z=86.50], EntityBat['Bat'/121, l='MpServer', x=-60.63, y=33.26, z=84.65], EntityBat['Bat'/122, l='MpServer', x=-67.25, y=62.10, z=112.57], HandEntity['Python Hand'/123, l='MpServer', x=-70.50, y=69.00, z=138.50], HandEntity['Python Hand'/124, l='MpServer', x=-71.50, y=69.00, z=137.50], EntityBat['Bat'/125, l='MpServer', x=-72.46, y=35.10, z=155.13], EntityBat['Bat'/126, l='MpServer', x=-71.86, y=12.01, z=198.65], EntityBat['Bat'/127, l='MpServer', x=-72.81, y=17.29, z=209.52]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 4.8.12-300.fc25.x86_64
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 343671776 bytes (327 MB) / 750891008 bytes (716 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAAAA	pycode{1.3} [Python Code] (pycode-1.3.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel Open Source Technology Center' Version: '3.0 Mesa 13.0.2' Renderer: 'Mesa DRI Intel(R) Haswell Mobile '
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2185
	LWJGL: 2.9.4
	OpenGL: Mesa DRI Intel(R) Haswell Mobile  GL version 3.0 Mesa 13.0.2, Intel Open Source Technology Center
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz

**Comment by r1chardj0n3s** [comment]
I've been unable to reproduce the error above, do you have any clue how to reproduce?

I'm still mulling over whether to keep pages or switch to scrolling...

**Comment by r1chardj0n3s** [comment]
I should see how much of https://github.com/SlimeKnights/Mantle/tree/master/src/main/java/slimeknights/mantle/client/gui book implementation (and slider, etc) I could pull in as a library...

**Comment by r1chardj0n3s** [comment]
I found a bug in page changing code which caused a crash due to bad cursor positioning after page change, which is most likely the cause of the crash reported above. I've also re-arranged the book GUI layout to make pagination clearer (amongst other things).
